services:
  apache-service:
    container_name: myotherwebsite
    image: httpd:latest
    cpus: 1.5
    mem_limit: 2048m
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs
  nginx-service:
    container_name: nginx-app
    image: nginx:latest
    cpus: 2.5
    mem_limit: 4096m
    ports:
      - "99:80"
    volumes:
      - ./nginx-app:/usr/share/nginx/html
  tomcat-service:
    container_name: sample-war
    image: tomcat:latest
    cpus: 3.5
    mem_limit: 4096m
    ports:
      - "8080:8080"
    volumes:
      - ./samplewar:/usr/local/tomcat/webapps
  tomcat-service2:
    container_name: sample-jar
    image: java-jar-image:latest
    cpus: 3.5
    mem_limit: 4096m
    ports:
      - "8081:8080"
    volumes:
      - ./samplewar:/usr/local/tomcat/webapps
