services:
  apache-s:
    container_name: website-c
    image: httpd:latest
    cpus: 1.5
    mem_limit: 2048m
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs
  nginx-s:
    container_name: nginx-c
    image: nginx:latest
    cpus: 2.5
    mem_limit: 4096m
    ports:
      - "99:80"
    volumes:
      - ./nginx-app:/usr/share/nginx/html
  tomcat-s:
    container_name: samplewar-c
    image: tomcat:latest
    cpus: 3.5
    mem_limit: 4096m
    ports:
      - "8080:8080"
    volumes:
      - ./samplewar:/usr/local/tomcat/webapps
  tomcat-s2:
    container_name: jar-c
    image: jar-i:latest
    cpus: 3.5
    mem_limit: 4096m
    ports:
      - "8081:8080"
    volumes:
      - ./samplewar:/usr/local/tomcat/webapps
