services:
  # Versión de
  # https://youtu.be/6hMHziv0T2Y
  # Dockerize Spring Boot Application with MySQL using Docker compose
  mysqldb:
    # Solo en Linux. En Windows no va. ¡JA ja ja !
    # platforn: linux/x86_64
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: anime
      MYSQL_USER: cruduser
      MYSQL_PASSWORD: 1234
      # Mandatorio, pero puede ser cualquier cosa
      MYSQL_ROOT_PASSWORD: 123456
    # Este script se va a ejecutar la primera vez, y es un modo de
    # inicializar la base de datos. Esto lo podría hacer manualmente,
    # pero de este modo es automático.
    volumes:
      - "./sql/anime.sql:/docker-entrypoint-initdb.d/1.sql"
  server:
    build: .
    # Este servicio depende de mysqldb. Si la base de datos no arrancó,
    # no se puede conectar. Pero puede pasar que no haya nada mal,
    # y que solo necesite más tiempo. Por eso le digo que siga intentando
    # arrancar hasta que pueda.
    restart: always
    ports:
      - 8080:8080
    depends_on:
      # acá va el nombre de un servicio, no de un container
      - mysqldb
