services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: anime
      MYSQL_USER: cruduser
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 4321
